loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 2
  storage:
    type: 's3'
    bucketNames:
      chunks: "your-loki-chunks-bucket"
      ruler: "your-loki-ruler-bucket"
      admin: "your-loki-admin-bucket"
    s3:
      endpoint: "s3.ap-south-1.amazonaws.com"
      region: "ap-south-1"
      secretAccessKey: "$AWS_SECRET_ACCESS_KEY"  # Set via secret
      accessKeyId: "$AWS_ACCESS_KEY_ID"          # Set via secret

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki-gateway/loki/api/v1/push
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: "kong|directus|emqx"