apiVersion: apps/v1
kind: Deployment
metadata:
  name: directus
  namespace: directus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directus
  template:
    metadata:
      labels:
        app: directus
    spec:
      containers:
      - name: directus
        image: directus/directus:latest
        ports:
        - containerPort: 8055
        env:
        - name: DB_CLIENT
          value: "pg"
        - name: DB_HOST
          value: "pgbouncer-service"
        - name: DB_PORT
          value: "6432"
        - name: DB_DATABASE
          value: "directus"
        - name: DB_USER
          value: "directus_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: PUBLIC_URL
          value: https://api.samaypayroll.com/directus