_format_version: "3.0"
_transform: true

services:
  - name: directus-service
    url: http://directus-service.senzr.svc.cluster.local:8055
    routes:
      - name: directus-route
        paths:
          - "/"
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Authorization
            - Content-Type
            - X-Requested-With
          credentials: true
          max_age: 3600
          preflight_continue: false
