_format_version: "3.0"
services:
  - name: directus-service
    url: http://directus-service.senzr.svc.cluster.local:8055
    routes:
      - name: directus-server-route
        paths:
          - /server
        strip_path: false
        preserve_host: true
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
                - OPTIONS
              headers:
                - Accept
                - Content-Type
                - Authorization
              credentials: true
      - name: directus-api-route
        paths:
          - /api
        strip_path: false
        preserve_host: true
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
                - OPTIONS
              headers:
                - Accept
                - Content-Type
                - Authorization
              credentials: true
      - name: directus-admin-route
        paths:
          - /admin
        strip_path: false
        preserve_host: true
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
                - OPTIONS
              headers:
                - Accept
                - Content-Type
                - Authorization
              credentials: true
      - name: directus-auth-route
        paths:
          - /auth
        strip_path: false
        preserve_host: true
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
                - OPTIONS
              headers:
                - Accept
                - Content-Type
                - Authorization
              credentials: true
      - name: directus-assets-route
        paths:
          - /assets
        strip_path: false
        preserve_host: true
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
                - OPTIONS
              headers:
                - Accept
                - Content-Type
                - Authorization
              credentials: true

plugins:
  - name: rate-limiting
    config:
      minute: 100
      hour: 1000
