_format_version: "3.0"
_transform: true

services:
- name: directus-service
  url: http://directus-service.senzr.svc.cluster.local:8055
  routes:
  - name: directus-root-route
    paths:
    - /
    strip_path: false
    preserve_host: false
    methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
    - HEAD
    protocols:
    - http
    - https
    plugins:
    - name: cors
      config:
        origins:
        - "*"
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
        headers:
        - Accept
        - Content-Length
        - Content-Type
        - Authorization
        - X-Auth-Token
        exposed_headers:
        - X-Auth-Token
        credentials: true
        max_age: 3600
