apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-ha-config
  namespace: senzr
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    requirepass senzr-redis-2025

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-ha
  namespace: senzr
spec:
  serviceName: redis-ha-headless
  replicas: 3
  selector:
    matchLabels:
      app: redis-ha
  template:
    metadata:
      labels:
        app: redis-
