apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-master-config
  namespace: senzr
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    requirepass "senzr-redis-2025"
    masterauth "senzr-redis-2025"
    appendonly yes
    databases 16
    maxmemory 896mb
    maxmemory-policy allkeys-lru
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-replica-config
  namespace: senzr
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    requirepass "senzr-redis-2025"
    masterauth "senzr-redis-2025"
    replicaof redis-master-service 6379
    replica-read-only yes
    appendonly yes
    databases 16
    maxmemory 512mb
    maxmemory-policy allkeys-lru
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config
  namespace: senzr
data:
  sentinel.conf: |
    port 26379
    bind 0.0.0.0
    sentinel monitor redis-main redis-master-service 6379 2
    sentinel auth-pass redis-main "senzr-redis-2025"
    sentinel down-after-milliseconds redis-main 30000
    sentinel failover-timeout redis-main 180000
    sentinel parallel-syncs redis-main 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: senzr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
      - name: redis
        image: redis:7.2-alpine
        ports:
        - containerPort: 6379
        command: ["redis-server", "/etc/redis/redis.conf"]
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: redis-config
        configMap:
          name: redis-master-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
  namespace: senzr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-replica
  template:
    metadata:
      labels:
        app: redis-replica
    spec:
      containers:
      - name: redis
        image: redis:7.2-alpine
        ports:
        - containerPort: 6379
        command: ["redis-server", "/etc/redis/redis.conf"]
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
      volumes:
      - name: redis-config
        configMap:
          name: redis-replica-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel
  namespace: senzr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
      - name: sentinel
        image: redis:7.2-alpine
        ports:
        - containerPort: 26379
        command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
        volumeMounts:
        - name: sentinel-config
          mountPath: /etc/redis/
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: sentinel-config
        configMap:
          name: redis-sentinel-config
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master-service
  namespace: senzr
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-master
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-service
  namespace: senzr
spec:
  ports:
  - port: 26379
    targetPort: 26379
  selector:
    app: redis-sentinel
