adminUser: admin
adminPassword: "$GF_SECURITY_ADMIN_PASSWORD"  # Set via Kubernetes secret

persistence:
  enabled: true
  storageClassName: "ebs-sc"
  size: 10Gi

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true

grafana.ini:
  server:
    domain: "grafana.yourdomain.com"
    root_url: "%(protocol)s://%(domain)s/"