architecture: replication
auth:
  enabled: true
  password: "$REDIS_PASSWORD"  # Set via secret

master:
  persistence:
    enabled: true
    storageClass: "ebs-sc"
    size: "10Gi"

replica:
  replicaCount: 2
  persistence:
    enabled: true
    size: "10Gi"

sentinel:
  enabled: true