apiVersion: v1
kind: Service
metadata:
  name: emqx-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Network LB for MQTT
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
    - name: mqtts
      port: 8883
      targetPort: 8883
      protocol: TCP
    - name: ws
      port: 8083
      targetPort: 8083
      protocol: TCP
    - name: wss
      port: 8084
      targetPort: 8084
      protocol: TCP
    - name: dashboard
      port: 18083
      targetPort: 18083
      protocol: TCP
  selector:
    app.kubernetes.io/name: emqx
  externalTrafficPolicy: Local  # Preserve client IP