apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: directus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
      - name: pgbouncer
        image: edoburu/pgbouncer:1.18.0
        ports:
        - containerPort: 6432
        env:
        - name: DB_HOST
          value: "samay-db-cluster.cjguq2ma02dv.ap-south-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "directus_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: POOL_MODE
          value: "transaction"
        - name: MAX_CLIENT_CONN
          value: "1000"
        - name: DEFAULT_POOL_SIZE
          value: "25"
---
apiVersion: v1

kind: Service
metadata:
  name: pgbouncer-service
  namespace: directus
spec:
  selector:
    app: pgbouncer
  ports:
  - port: 6432
    targetPort: 6432
  type: ClusterIP