apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: senzr
type: Opaque
data:
  password: U2VuenJEQjEyMyE=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: senzr
  labels:
    app: pgbouncer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
      - name: pgbouncer
        image: pgbouncer/pgbouncer:latest
        ports:
        - containerPort: 5432
        env:
        - name: DATABASES_HOST
          value: "directus-postgres.cjguq2ma02dv.ap-south-1.rds.amazonaws.com"
        - name: DATABASES_PORT
          value: "5432"
        - name: DATABASES_USER
          value: "directus"
        - name: DATABASES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POOL_MODE
          value: "transaction"
        - name: MAX_CLIENT_CONN
          value: "100"
        - name: DEFAULT_POOL_SIZE
          value: "20"
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: senzr
spec:
  selector:
    app: pgbouncer
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP[Copy PgBouncer YAML content from artifact]
