apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: emqx-cluster
  region: ap-south-1

nodeGroups:
  - name: emqx-nodes-new
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        efs: true
        albIngress: true
